### ISSUE TITLE
fail to import TextDrawer

### ISSUE THREAD

**Issue by Textcat** [remirobert/TextDrawer#5]
Thanks for your work. fail to import TextDrawer , "No such module TextDrawer"

**Comment by remirobert** [comment]
How did you install **TextDrawer** ? 
- If you just move the source in your project, you don't need to import it
- If you install it with **cocoapods** please use `use_frameworks!` in your Podfile.

Then you will be able to import it.

**Comment by Textcat** [comment]
Work nicely now, thanks  :-D . I fixed some error about ? or ! , hope won't cause problem in the future

**Comment by remirobert** [comment]
Hum, I will check that for the ! and ?. Be free to create a pull request if you want also.
Thank you for you feedback.
