### ISSUE TITLE
part of the rendered image is redundant

### ISSUE THREAD

**Issue by Textcat** [remirobert/TextDrawer#8]
Hi, I have a imageView in my project and I render some text on the imageView' image. As the imageView 's mode is "aspect fit" (and the image didn't fill it), it has some spare space. And the rendered image keep these redundant space which I don't want.You can have a look at the screenshot below.

Will TextDrawer cause the issue? Or I did something wrong?
<img width="400" alt="2016-04-10 10 54 51" src="https://cloud.githubusercontent.com/assets/10849914/14411104/91f04382-ff71-11e5-9200-85b721bde966.png">

**Comment by remirobert** [comment]
Yes That's a normal behaviour. Because TextDrawer, doesn't care about your image size. What matters is only the UIView, where you want to draw your stuff. That means, if you have a aspect ratio on your image, you will have some border.

**Comment by Textcat** [comment]
Thanks for your reply. I solve the problem by set the bounds of textDrawer view exactly equal to the scaled image.
